---
version: '3'
services:

  database:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5050:5432"

  webapp:
    build: .
    ports:
      - "5000:5000"
    command: python3 main.py
    depends_on:
      - database
